# import = ["/home/joshru/.config/alacritty/dracula.toml"]
import = ["/home/joshru/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "tmux"

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font"
